# suppress inspection "UnusedProperty" for whole file
archunitVersion=1.3.0
arthasSpringBootVersion=4.0.4
classgraphVersion=4.8.179
datasourceDecoratorVersion=1.10.0
dbSchedulerVersion=15.1.1
easyexcelVersion=4.0.3
# ebean
ebeanVersion=15.8.1
guavaVersion=33.4.0-jre
handlebarsVersion=4.3.1
hutoolVersion=6.0.0-M19
ip2regionVersion=2.7.0
jetbrainsAnnotationsVersion=26.0.1
jsr305Version=3.0.2
logviewerVersion=1.0.11
magicApiVersion=2.1.1
mapstructVersion=1.6.3
minioVersion=8.5.14
p6spyVersion=3.9.1
playtikaVersion=3.1.10
poiTlVersion=1.12.3-beta1
redissonVersion=3.41.0
retrofitSpringBootVersion=3.1.3
saTokenVersion=1.39.0
springBootAdminVersion=3.4.1
springBootVersion=3.4.0
springdocVersion=2.7.0
xFileStorageVersion=2.2.1
testcontainersVersion=1.20.4
tianaiCaptchaVersion=1.5.1
tlogVersion=1.5.2
transmittableThreadLocalVersion=2.14.5
wxJavaVersion=4.7.0
zonkyVersion=2.1.0
zonkyPostgresVersion=17.2.0
zonkySpringVersion=2.6.0