# suppress inspection "UnusedProperty" for whole file
archunitVersion=1.3.0
arthasSpringBootVersion=4.0.2
classgraphVersion=4.8.177
datasourceDecoratorVersion=1.9.2
dbSchedulerVersion=14.1.0
easyexcelVersion=4.0.3
# ebean
ebeanVersion=15.8.0
guavaVersion=33.3.1-jre
handlebarsVersion=4.3.1
hutoolVersion=6.0.0-M17
ip2regionVersion=2.7.0
jetbrainsAnnotationsVersion=26.0.1
jsr305Version=3.0.2
logviewerVersion=1.0.11
magicApiVersion=2.1.1
mapstructVersion=1.6.2
minioVersion=8.5.13
p6spyVersion=3.9.1
playtikaVersion=3.1.9
poiTlVersion=1.12.3-beta1
redissonVersion=3.38.1
retrofitSpringBootVersion=3.1.3
saTokenVersion=1.39.0
springBootAdminVersion=3.3.4
springBootVersion=3.3.5
springdocVersion=2.6.0
xFileStorageVersion=2.2.1
testcontainersVersion=1.20.3
tianaiCaptchaVersion=1.5.1
tlogVersion=1.5.2
transmittableThreadLocalVersion=2.14.5
wxJavaVersion=4.6.6.B
zonkyVersion=2.0.7
zonkyPostgresVersion=17.0.0
zonkySpringVersion=2.5.1