rootProject.name = "jany"
include("jany-archunit")
include("jany-core")
include("jany-ebean")
include("jany-jooq")
include("jany-jooq-codegen")
include("jany-jackson")
include("jany-p6spy")
include("jany-platform")
include("jany-spring")
include("jany-spring-boot-starter")
include("jany-spring-boot-starter-springdoc")
include("jany-spring-boot-starter-handlebars")
include("jany-spring-boot-starter-p6spy")
include("jany-spring-boot-starter-minio")
include("jany-test")
include("jany-validation")