# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    paths:
      - '**.java'
      - '**/build.gradle.kts'
      - 'gradle.properties'
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{matrix.java}}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          publicReleasesRepoUrl: ${{secrets.PUBLICRELEASESREPOURL}}
          publicSnapshotsRepoUrl: ${{secrets.PUBLICSNAPSHOTSREPOURL}}
          publicRepoUsername: ${{secrets.PUBLICREPOUSERNAME}}
          publicRepoPassword: ${{secrets.PUBLICREPOPASSWORD}}
        run: ./gradlew build
      - name: codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: bash <(curl -s https://codecov.io/bash)